<?php

namespace Database\Seeders;

use App\Models\School;
use App\Models\Students;
use App\Models\Questionnaire;
use App\Models\Infrastructure;
use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Articles;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
        User::create(['name' => 'admin', 'username' => 'admin', 'password' => bcrypt('password'), 'image' => 'default.webp', 'role' => 1, 'is_active' => 1]);
        User::create(['name' => 'admin2', 'username' => 'admin2', 'password' => bcrypt('password'), 'image' => 'default.webp', 'role' => 1, 'is_active' => 2]);
        User::create(['name' => 'admin3', 'username' => 'admin3', 'password' => bcrypt('password'), 'image' => 'default.webp', 'role' => 1, 'is_active' => 2]);
        User::create(['name' => 'user', 'username' => 'user', 'password' => bcrypt('password'), 'image' => 'default.webp', 'role' => 2, 'is_active' => 1]);
        User::create(['name' => 'user2', 'username' => 'user2', 'password' => bcrypt('password'), 'image' => 'default.webp', 'role' => 2, 'is_active' => 2]);

        Students::create(['name' => 'Siswa 1 SMA N 12', 'nisn' => '11223344', 'school_id' => '1']);
        Students::create(['name' => 'Siswa 2 SMA N 12', 'nisn' => '22334455', 'school_id' => '1']);
        Students::create(['name' => 'Siswa 3 SMA N 12', 'nisn' => '33445566', 'school_id' => '1']);
        Students::create(['name' => 'Siswa 1 SMA N 1', 'nisn' => '11223344', 'school_id' => '2']);
        Students::create(['name' => 'Siswa 1 SMA N 1', 'nisn' => '22334455', 'school_id' => '2']);
        Students::create(['name' => 'Siswa 2 SMA N 1', 'nisn' => '33445566', 'school_id' => '2']);
        Students::create(['name' => 'Siswa 2 SMA N 3', 'nisn' => '11223344', 'school_id' => '3']);
        Students::create(['name' => 'Siswa 3 SMA N 3', 'nisn' => '22334455', 'school_id' => '3']);
        Students::create(['name' => 'Siswa 3 SMA N 3', 'nisn' => '33445566', 'school_id' => '3']);
        Students::create(['name' => 'Siswa 1 SMP IT Insan Cendekia', 'nisn' => '11223344', 'school_id' => '4']);
        Students::create(['name' => 'Siswa 2 SMP IT Insan Cendekia', 'nisn' => '22334455', 'school_id' => '4']);
        Students::create(['name' => 'Siswa 3 SMP IT Insan Cendekia', 'nisn' => '33445566', 'school_id' => '4']);
        Students::create(['name' => 'Siswa 1 SMP N 13', 'nisn' => '11223344', 'school_id' => '5']);
        Students::create(['name' => 'Siswa 2 SMP N 13', 'nisn' => '22334455', 'school_id' => '5']);
        Students::create(['name' => 'Siswa 3 SMP N 13', 'nisn' => '33445566', 'school_id' => '5']);
        Students::create(['name' => 'Siswa 1 MTs Al Asror', 'nisn' => '11223344', 'school_id' => '6']);
        Students::create(['name' => 'Siswa 2 MTs Al Asror', 'nisn' => '22334455', 'school_id' => '6']);
        Students::create(['name' => 'Siswa 3 MTs Al Asror', 'nisn' => '33445566', 'school_id' => '6']);
        Students::create(['name' => 'Siswa 1 SDN Bendan Ngisor', 'nisn' => '11223344', 'school_id' => '7']);
        Students::create(['name' => 'Siswa 2 SDN Bendan Ngisor', 'nisn' => '22334455', 'school_id' => '7']);
        Students::create(['name' => 'Siswa 3 SDN Bendan Ngisor', 'nisn' => '33445566', 'school_id' => '7']);
        Students::create(['name' => 'Siswa 1 SDN Petompon 2', 'nisn' => '11223344', 'school_id' => '8']);
        Students::create(['name' => 'Siswa 2 SDN Petompon 2', 'nisn' => '22334455', 'school_id' => '8']);
        Students::create(['name' => 'Siswa 3 SDN Petompon 2', 'nisn' => '33445566', 'school_id' => '8']);
        Students::create(['name' => 'Siswa 1 SDN Sukorejo 2', 'nisn' => '11223344', 'school_id' => '9']);
        Students::create(['name' => 'Siswa 2 SDN Sukorejo 2', 'nisn' => '22334455', 'school_id' => '9']);
        Students::create(['name' => 'Siswa 3 SDN Sukorejo 2', 'nisn' => '33445566', 'school_id' => '9']);

        School::create([
            'name' => 'SMA NEGERI 12',
            'npsn' => '20328911',
            'bp' => 'SMA',
            'status' => 'Negeri',
            'status_kepemilikan' => 'Pemerintah Daerah',
            'sk_pendirian' => '-',
            'sk_pendirian_tanggal' => '-',
            'sk_ijin_operasional' => '-',
            'sk_ijin_operasional_tanggal' => '-',
            'kepsek' => 'Endah Dyah Wardani',
            'akreditasi' => 'A',
            'kurikulum' => 'Kurikulum 2013',
        ]);

        School::create([
            'name' => 'SMA NEGERI 01',
            'npsn' => '20328867',
            'bp' => 'SMA',
            'status' => 'Negeri',
            'status_kepemilikan' => 'Pemerintah Daerah',
            'sk_pendirian' => '3412/B/III',
            'sk_pendirian_tanggal' => '1955-07-01',
            'sk_ijin_operasional' => '035/0/1997',
            'sk_ijin_operasional_tanggal' => '1997-03-07',
            'kepsek' => 'Kusno',
            'akreditasi' => 'A',
            'kurikulum' => 'Kurikulum 2013',
        ]);

        School::create([
            'name' => 'SMA NEGERI 03',
            'npsn' => '20328895',
            'bp' => 'SMA',
            'status' => 'Negeri',
            'status_kepemilikan' => 'Pemerintah Daerah',
            'sk_pendirian' => '035/0/197',
            'sk_pendirian_tanggal' => '1997-03-07',
            'sk_ijin_operasional' => '035/0/197',
            'sk_ijin_operasional_tanggal' => '1997-03-07',
            'kepsek' => 'Yuwana',
            'akreditasi' => 'A',
            'kurikulum' => 'Kurikulum 2013',
        ]);

        School::create([
            'name' => 'SMP IT INSAN CENDEKIA',
            'npsn' => '69828771',
            'bp' => 'SMP',
            'status' => 'Swasta',
            'status_kepemilikan' => 'Yayasan',
            'sk_pendirian' => '421.7/1044/2014',
            'sk_pendirian_tanggal' => '2014-02-27',
            'sk_ijin_operasional' => '421.7/1044/2014',
            'sk_ijin_operasional_tanggal' => '2014-02-27',
            'kepsek' => 'Aproni',
            'akreditasi' => 'B',
            'kurikulum' => 'Kurikulum 2013',
        ]);

        School::create([
            'name' => 'SMP NEGERI 13',
            'npsn' => '20328824',
            'bp' => 'SMP',
            'status' => 'Negeri',
            'status_kepemilikan' => 'Pemerintah Daerah',
            'sk_pendirian' => '030/U/1979',
            'sk_pendirian_tanggal' => '1979-04-01',
            'sk_ijin_operasional' => '480/C/1992',
            'sk_ijin_operasional_tanggal' => '1992-12-15',
            'kepsek' => 'Sri Wasetyastuti',
            'akreditasi' => 'A',
            'kurikulum' => 'Kurikulum 2013',
        ]);

        School::create([
            'name' => 'MTs AL ASROR',
            'npsn' => '20364826',
            'bp' => 'SMP',
            'status' => 'Swasta',
            'status_kepemilikan' => '-',
            'sk_pendirian' => '-',
            'sk_pendirian_tanggal' => '-',
            'sk_ijin_operasional' => '-',
            'sk_ijin_operasional_tanggal' => '-',
            'kepsek' => 'Agung Sudaryanto,S.Pd',
            'akreditasi' => 'A',
            'kurikulum' => 'Kurikulum 2013',
        ]);

        School::create([
            'name' => 'SD NEGERI BENDAN NGISOR',
            'npsn' => '20329403',
            'bp' => 'SD',
            'status' => 'Negeri',
            'status_kepemilikan' => 'Pemerintah Daerah',
            'sk_pendirian' => '421.2/001/IV/92/85',
            'sk_pendirian_tanggal' => '1985-10-01',
            'sk_ijin_operasional' => '-',
            'sk_ijin_operasional_tanggal' => '-',
            'kepsek' => 'Kapuranti, S. Pd',
            'akreditasi' => 'A',
            'kurikulum' => 'Kurikulum 2013',
        ]);

        School::create([
            'name' => 'SD NEGERI PETOMPON 02',
            'npsn' => '20328751',
            'bp' => 'SD',
            'status' => 'Negeri',
            'status_kepemilikan' => 'Pemerintah Daerah',
            'sk_pendirian' => '420/4610',
            'sk_pendirian_tanggal' => '2010-08-25',
            'sk_ijin_operasional' => '420/4610',
            'sk_ijin_operasional_tanggal' => '2010-08-25',
            'kepsek' => 'Suwiji',
            'akreditasi' => 'A',
            'kurikulum' => 'Kurikulum 2013',
        ]);

        School::create([
            'name' => 'SD NEGERI SUKOREJO 02',
            'npsn' => '20328565',
            'bp' => 'SD',
            'status' => 'Negeri',
            'status_kepemilikan' => 'Pemerintah Daerah',
            'sk_pendirian' => '-',
            'sk_pendirian_tanggal' => '-',
            'sk_ijin_operasional' => '-',
            'sk_ijin_operasional_tanggal' => '-',
            'kepsek' => 'Ary Sotyarini',
            'akreditasi' => 'A',
            'kurikulum' => 'Kurikulum 2013',
        ]);

        Questionnaire::create(['question' => 'Luas Sekolah']);
        Questionnaire::create(['question' => 'Luas Ruang Terbuka']);
        Questionnaire::create(['question' => 'Jumlah Kelas']);
        Questionnaire::create(['question' => 'Luas Ruang Kelas']);
        Questionnaire::create(['question' => 'Ketersediaan Ventilasi']);

        Questionnaire::create(['question' => 'Jumlah Guru']);
        Questionnaire::create(['question' => 'Jumlah Siswa']);
        Questionnaire::create(['question' => 'Jumlah Tenaga Administrasi']);

        Questionnaire::create(['question' => 'Jumlah Toilet']);
        Questionnaire::create(['question' => 'Ketersedian Air di Toilet']);
        Questionnaire::create(['question' => 'Ketersediaan Sabun Cuci Tangan di Depan Kelas']);
        Questionnaire::create(['question' => 'Disinfektan Toilet']);
        Questionnaire::create(['question' => 'Ketersediaan Tempat Cuci Tangan di Depan Kelas']);
        Questionnaire::create(['question' => 'Ketersediaan Handsanitizer']);
        Questionnaire::create(['question' => 'Ketersediaan Thermogun']);
        Questionnaire::create(['question' => 'Ketersediaan Masker']);
        Questionnaire::create(['question' => 'Ketaatan Penggunaan Masker']);

        Questionnaire::create(['question' => 'Ketersediaan Satgas Covid-19']);
        Questionnaire::create(['question' => 'Sosialisasi Protokol Kesehatan']);
        Questionnaire::create(['question' => 'Ketersediaan Prosedur Penanganan Covid-19']);
        Questionnaire::create(['question' => 'Ketersediaan Media Informasi Covid-19']);
        Questionnaire::create(['question' => 'Ketersediaan Peraturan/Tata Tertib Covid-19']);
        Questionnaire::create(['question' => 'Ketersediaan Kantin Sehat']);

        Questionnaire::create(['question' => 'Data Covid-19 Tahunan']);
        Questionnaire::create(['question' => 'Data Covid-19 Per Bulan']);
        Questionnaire::create(['question' => 'Pemusatan Covid-19 pada Kelas Tertentu']);

        Articles::create([
            'user_id' => 1, 'title' => 'artikel pertama', 'slug' => 'artikel-pertama',
            'exerpt' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit',
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br>Nemo cumque temporibus dolor voluptates perspiciatis a in voluptatum impedit quibusdam, nobis nisi expedita quidem. Qui maxime aliquid nam, harum perspiciatis, nobis accusantium similique explicabo facere repellendus illum quas dignissimos alias dolores voluptatibus sequi assumenda facilis consequatur nostrum sit autem voluptate. <br>Ratione recusandae ipsum veniam nemo reprehenderit vero vel aliquam dolores quaerat.'
        ]);
        Articles::create([
            'user_id' => 1, 'title' => 'artikel kedua', 'slug' => 'artikel-kedua',
            'exerpt' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit',
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br>Nemo cumque temporibus dolor voluptates perspiciatis a in voluptatum impedit quibusdam, nobis nisi expedita quidem. Qui maxime aliquid nam, harum perspiciatis, nobis accusantium similique explicabo facere repellendus illum quas dignissimos alias dolores voluptatibus sequi assumenda facilis consequatur nostrum sit autem voluptate. <br>Ratione recusandae ipsum veniam nemo reprehenderit vero vel aliquam dolores quaerat.'
        ]);
        Articles::create([
            'user_id' => 1, 'title' => 'artikel ketiga', 'slug' => 'artikel-ketiga',
            'exerpt' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit',
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br>Nemo cumque temporibus dolor voluptates perspiciatis a in voluptatum impedit quibusdam, nobis nisi expedita quidem. Qui maxime aliquid nam, harum perspiciatis, nobis accusantium similique explicabo facere repellendus illum quas dignissimos alias dolores voluptatibus sequi assumenda facilis consequatur nostrum sit autem voluptate. <br>Ratione recusandae ipsum veniam nemo reprehenderit vero vel aliquam dolores quaerat.'
        ]);
        Articles::create([
            'user_id' => 1, 'title' => 'artikel keempat', 'slug' => 'artikel-keempat',
            'exerpt' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit',
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br>Nemo cumque temporibus dolor voluptates perspiciatis a in voluptatum impedit quibusdam, nobis nisi expedita quidem. Qui maxime aliquid nam, harum perspiciatis, nobis accusantium similique explicabo facere repellendus illum quas dignissimos alias dolores voluptatibus sequi assumenda facilis consequatur nostrum sit autem voluptate. <br>Ratione recusandae ipsum veniam nemo reprehenderit vero vel aliquam dolores quaerat.'
        ]);
        Articles::create([
            'user_id' => 1, 'title' => 'artikel kelima', 'slug' => 'artikel-kelima',
            'exerpt' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit',
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br>Nemo cumque temporibus dolor voluptates perspiciatis a in voluptatum impedit quibusdam, nobis nisi expedita quidem. Qui maxime aliquid nam, harum perspiciatis, nobis accusantium similique explicabo facere repellendus illum quas dignissimos alias dolores voluptatibus sequi assumenda facilis consequatur nostrum sit autem voluptate. <br>Ratione recusandae ipsum veniam nemo reprehenderit vero vel aliquam dolores quaerat.'
        ]);
        Articles::create([
            'user_id' => 1, 'title' => 'artikel keenam', 'slug' => 'artikel-keenam',
            'exerpt' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit',
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br>Nemo cumque temporibus dolor voluptates perspiciatis a in voluptatum impedit quibusdam, nobis nisi expedita quidem. Qui maxime aliquid nam, harum perspiciatis, nobis accusantium similique explicabo facere repellendus illum quas dignissimos alias dolores voluptatibus sequi assumenda facilis consequatur nostrum sit autem voluptate. <br>Ratione recusandae ipsum veniam nemo reprehenderit vero vel aliquam dolores quaerat.'
        ]);

        // SMA NEGERI 12 [1]
        Infrastructure::create([
            'school_id' => 1, 'school_address' => 'Jl. Raya Gunungpati, Kota Semarang', 'school_bp' => 'SMA',
            'A1' => '14329',
            'A2' => '450',
            'A3' => '36',
            'A4' => '72',
            'A5' => '1.92',
            'B1' => '71',
            'B2' => '1278',
            'B3' => '496',
            'B4' => '782',
            'B5' => '12',
            'C1' => '17',
            'C2' => '21',
            'C3' => 'Baik',
            'C4' => '36',
            'C5' => '1',
            'C6' => '36',
            'C7' => '36',
            'C8' => '2',
            'C9' => '50',
            'C10' => 'Baik',
            'D1' => 'Ya',
            'D2' => 'Ya',
            'D3' => 'Ya',
            'D4' => 'Ya',
            'D5' => 'Ya',
            'D6' => 'Ya',
            'E1' => '0',
            'E2' => '0',
            'E3' => 'Tidak',
            'explanation_A1' => '14.329 m2',
            'explanation_A2' => '450 m2',
            'explanation_A3' => '36 kelas',
            'explanation_A4' => '8 m × 9 m = 72 m2',
            'explanation_A5' => '8 buah (0,4 m × 0,6 m)',
            'explanation_B1' => '71 orang (Laki-laki = 33 orang, Perempuan = 38 orang)',
            'explanation_B2' => '1.278 orang, tiap kelas 36 orang',
            'explanation_B3' => 'Laki-laki = 496 orang',
            'explanation_B4' => 'Perempuan = 782 orang',
            'explanation_B5' => '12 orang (Laki-laki = 7 orang, Perempuan = 5 orang)',
            'explanation_C1' => 'Laki-laki = 17',
            'explanation_C2' => 'Perempuan = 21',
            'explanation_C3' => 'Ya selalu mengalir (ember dan keran air mengalir)',
            'explanation_C4' => 'Jumlah yang disediakan 36 sabun cuci tangan dibagi dengan jumlah kelas 36',
            'explanation_C5' => 'Dibersihkan setiap seminggu sekali',
            'explanation_C6' => 'Jumlah yang disediakan 36 tempat cuci tangan dibagi dengan jumlah kelas 36',
            'explanation_C7' => 'Jumlah handsanitizer yang disediakan 36 dibagi dengan jumlah kelas 36',
            'explanation_C8' => 'Ada 2 thermogun (yang berdiri dan di tembok)',
            'explanation_C9' => 'Disediakan masker cadangan (50 pcs) dari jumlah siswa 1278',
            'explanation_C10' => 'Taat masker saat di kelas tetapi tidak memakai masker saat jam olahraga',
            'explanation_D1' => 'Ada satgas dari guru dengan berbagai macam mata pelajaran sebanyak 12 orang',
            'explanation_D2' => 'Ya dilakukan sosialisasi dengan memberikan PPT dan dijelaskan lisan saat awal pelajaran (di pagi hari)',
            'explanation_D3' => 'Langsung lapor puskesmas dan di karantina di ruang isolasi terpisah di sekolah sebelum di bawa ke rumah lalu wilayah orang yang terkana Covid-19 dilaporkan ke puskesmas',
            'explanation_D4' => 'Ya terdapat pamphlet madding dan slide PPT dari guru',
            'explanation_D5' => 'Ya di buat protokol kesehatan (siswa memakai masker, jaga jarak dan pengaturan penjemputan siswa)',
            'explanation_D6' => 'Kantin sehat dengan jenis jajanan dan proses penyajian yang tertutup',
            'explanation_E1' => 'Tidak ada kasus setahun terakhir tahun 2021 terdapat kasus 88 orang guru dan anak 17 orang',
            'explanation_E2' => 'Tidak ada kasus (0 kasus)',
            'explanation_E3' => 'Tidak ada pemusatan pada kelas tertentu karena yang terkena Covid-19 di suruh isolasi mandiri di rumah',
            'notes' => '',
        ]);
        // SMA NEGERI 01 [2]
        Infrastructure::create([
            'school_id' => 2, 'school_address' => 'Jl. Taman Menteri Supeno No 1 Semarang', 'school_bp' => 'SMA',
            'A1' => '43000',
            'A2' => '14300',
            'A3' => '36',
            'A4' => '81',
            'A5' => '28',
            'B1' => '72',
            'B2' => '1269',
            'B3' => '553',
            'B4' => '716',
            'B5' => '27',
            'C1' => '15',
            'C2' => '25',
            'C3' => 'Baik',
            'C4' => '18',
            'C5' => '1',
            'C6' => '18',
            'C7' => '36',
            'C8' => '1',
            'C9' => '50',
            'C10' => 'Baik',
            'D1' => 'Ya',
            'D2' => 'Ya',
            'D3' => 'Ya',
            'D4' => 'Ya',
            'D5' => 'Ya',
            'D6' => 'Ya',
            'E1' => '0',
            'E2' => '0',
            'E3' => 'Tidak',
            'explanation_A1' => '43.000 m2',
            'explanation_A2' => '±14.300 m2',
            'explanation_A3' => '36 kelas',
            'explanation_A4' => '81 m2 atau 9 × 9 m2',
            'explanation_A5' => '8 jendela besar (setiap jendela (2 m × 1 m atau 3 m2) dan 3 blok lubang angin  (2 m × 2 m atau 4 m2)',
            'explanation_B1' => '72 orang (laki-laki = 34 orang, perempuan = 38 orang)',
            'explanation_B2' => '1.269 siswa',
            'explanation_B3' => 'Laki-laki = 553 siswa',
            'explanation_B4' => 'Perempuan = 716 siswa',
            'explanation_B5' => '27 orang (laki-laki = 16 orang, perempuan = 11 orang',
            'explanation_C1' => 'Laki-laki 15 buah',
            'explanation_C2' => 'Perempuan 25 buah',
            'explanation_C3' => 'Selalu ada di ember dan mengalir juga',
            'explanation_C4' => 'Jumlah yang disediakan 18 sabun cuci tangan dibagi dengan jumlah kelas 36',
            'explanation_C5' => 'Dibersihkan setiap seminggu sekali',
            'explanation_C6' => 'Jumlah yang disediakan 18 tempat cuci tangan dibagi dengan jumlah kelas 36',
            'explanation_C7' => 'Jumlah handsanitizer yang disediakan 36 dibagi dengan jumlah kelas 36',
            'explanation_C8' => 'Dulu sering digunakan saat baru masuk ke lingkungan sekolah dan sekarang tidak lagi',
            'explanation_C9' => 'Disediakan masker cadangan (50 pcs) dari jumlah siswa 1269',
            'explanation_C10' => 'Ya masih menggunakan masker di kelas dan ketika di luar ruangan masih memakai tetapi akan tidak dipakai saat olahraga dan saat luar ruangan agak lengang',
            'explanation_D1' => 'Ada dengan guru, siswa sebagai satgas covid-19 di sekolah dan puskesmas pandanaran juga memantau',
            'explanation_D2' => 'Dilakukan sosialisasi dari DKK dan puskesmas pandanaran dan masih ada standee yang untuk memakai masker',
            'explanation_D3' => 'Langsung di suruh pulang Ketika baru gejala pusing, demam, batuk dan bersin',
            'explanation_D4' => 'Tersedia dengan WA grup, di Instagram, laman facebook, website dan masih ada standee di jalanan kea rah ruang kelas',
            'explanation_D5' => 'Ada dengan memakai masker, mencuci tangan sedangkan dulu awal 2021 PTMnya 12-15 anak, bulan berikutnya 50% PTM lalu mei 2022: 100% tetapi sampai jam 12 siang dan juli 2022 100% sudah sampai jam 15.30',
            'explanation_D6' => 'Ada dan menerapkan kantin sehat  dengan 2 tempat cuci tangan',
            'explanation_E1' => 'Setahun terakhir tidak ada kasus sedangkan dari awal covid sampai januari 2023 ada sebanyak 379 kasus',
            'explanation_E2' => 'Tidak ada',
            'explanation_E3' => 'Tidak ada pemusatan pada kelas tertentu karena yang terkena Covid-19 di suruh isolasi mandiri di rumah',
            'notes' => '',
        ]);
        // SMA NEGERI 03 [3]
        Infrastructure::create([
            'school_id' => 3, 'school_address' => 'Jl. Pemuda No 149 Semarang', 'school_bp' => 'SMA',
            'A1' => '17087',
            'A2' => '6000',
            'A3' => '36',
            'A4' => '72',
            'A5' => '14.4',
            'B1' => '72',
            'B2' => '1238',
            'B3' => '619',
            'B4' => '619',
            'B5' => '20',
            'C1' => '26',
            'C2' => '26',
            'C3' => 'Baik',
            'C4' => '36',
            'C5' => '1',
            'C6' => '36',
            'C7' => '36',
            'C8' => '1',
            'C9' => '50',
            'C10' => 'Baik',
            'D1' => 'Ya',
            'D2' => 'Ya',
            'D3' => 'Ya',
            'D4' => 'Ya',
            'D5' => 'Ya',
            'D6' => 'Ya',
            'E1' => '7',
            'E2' => '3',
            'E3' => 'Tidak',
            'explanation_A1' => '17.087 m2',
            'explanation_A2' => '6.000 m2',
            'explanation_A3' => '36 Kelas',
            'explanation_A4' => '72 m2 atau 8 × 9 m2',
            'explanation_A5' => '8 jendela (p = 1,2 m dan l = 1,5 m)',
            'explanation_B1' => '72 orang (laki-laki = 28 orang, perempuan = 44 orang)',
            'explanation_B2' => 'Total siswa 1238',
            'explanation_B3' => 'Laki-laki = 619',
            'explanation_B4' => 'Perempuan = 619',
            'explanation_B5' => '20 orang',
            'explanation_C1' => '26 buah',
            'explanation_C2' => '26 buah',
            'explanation_C3' => 'Selalu ada di ember dan mengalir juga',
            'explanation_C4' => 'Jumlah yang disediakan 36 sabun cuci tangan dibagi dengan jumlah kelas 36',
            'explanation_C5' => 'Dibersihkan setiap seminggu sekali',
            'explanation_C6' => 'Jumlah yang disediakan 36 tempat cuci tangan dibagi dengan jumlah kelas 36',
            'explanation_C7' => 'Jumlah handsanitizer yang disediakan 36 dibagi dengan jumlah kelas 36',
            'explanation_C8' => 'Ada thermogun dan sekarang sudah tidak digunakan untuk mengukur suhu tubuh',
            'explanation_C9' => 'Disediakan masker cadangan (50 pcs) dari jumlah siswa 1238',
            'explanation_C10' => 'Ya masih menggunakan masker di kelas dan ketika di luar ruangan masih memakai tetapi akan tidak dipakai saat olahraga dan saat luar ruangan agak lengang',
            'explanation_D1' => 'Ada dengan guru sebagai satgas covid-19',
            'explanation_D2' => 'Dilakukan secara lisan, MMT setiap kelas',
            'explanation_D3' => 'Orang tua melaporkan anaknya sakit ke sekolah atau dari puskesmas yang melaporkan ke guru (satgas Covid-19) bahwa ada siswa yang sakit',
            'explanation_D4' => 'Tersedia dengan adanya MMT dan banner',
            'explanation_D5' => 'Ada dengan memakai masker, mencuci tangan sebelum masuk UKS, perpustakaan dan laboratorium',
            'explanation_D6' => 'Ada dan menerapkan kantin sehat',
            'explanation_E1' => 'Setahun terakhir terdapat ± 7 kasus per kelas',
            'explanation_E2' => 'Setiap bulan ada ±3 kasus',
            'explanation_E3' => 'Tidak ada pemusatan pada kelas tertentu karena yang terkena Covid-19 di suruh isolasi mandiri di rumah',
            'notes' => '',
        ]);
        // SMP IT INSAN CENDEKIA [4]
        Infrastructure::create([
            'school_id' => 4, 'school_address' => 'Jl. Menoreh Raya No 83, Semarang', 'school_bp' => 'SMP',
            'A1' => '2880',
            'A2' => '1200',
            'A3' => '9',
            'A4' => '56',
            'A5' => '5.95',
            'B1' => '20',
            'B2' => '250',
            'B3' => '160',
            'B4' => '90',
            'B5' => '2',
            'C1' => '4',
            'C2' => '5',
            'C3' => 'Baik',
            'C4' => '3',
            'C5' => '1',
            'C6' => '3',
            'C7' => '9',
            'C8' => '1',
            'C9' => '50',
            'C10' => 'Tidak Baik',
            'D1' => 'Ya',
            'D2' => 'Ya',
            'D3' => 'Ya',
            'D4' => 'Tidak',
            'D5' => 'Ya',
            'D6' => 'Ya',
            'E1' => '0',
            'E2' => '0',
            'E3' => 'Tidak',
            'explanation_A1' => '2.880 m2',
            'explanation_A2' => '1200 m2',
            'explanation_A3' => '9 Kelas',
            'explanation_A4' => '7 m × 8 m = 56 m2',
            'explanation_A5' => '17 buah (0,5 m × 0,7 m)',
            'explanation_B1' => '20 orang (Laki-laki = 10 orang, Perempuan = 10 orang)',
            'explanation_B2' => '250 Siswa',
            'explanation_B3' => 'Laki-laki = 160 Siswa',
            'explanation_B4' => 'Perempuan = 90 Siswa',
            'explanation_B5' => '2 orang (Laki-laki = 1 orang, Perempuan = 1 orang)',
            'explanation_C1' => 'Laki-laki = 4 buah',
            'explanation_C2' => 'Perempuan = 5 buah',
            'explanation_C3' => 'Ya selalu mengalir (ember dan keran air mengalir)',
            'explanation_C4' => 'Jumlah yang disediakan 3 sabun cuci tangan dibagi dengan jumlah kelas 9',
            'explanation_C5' => 'Dibersihkan setiap seminggu sekali',
            'explanation_C6' => 'Jumlah yang disediakan 3 tempat cuci tangan dibagi dengan jumlah kelas 9',
            'explanation_C7' => 'Jumlah handsanitizer yang disediakan 9 dibagi dengan jumlah kelas 9',
            'explanation_C8' => 'Dulu ada dan selalu digunakan saat baru masuk ke sekolah',
            'explanation_C9' => 'Disediakan masker cadangan (50 pcs) dari jumlah siswa 250',
            'explanation_C10' => 'Dulu selalu bermasker dan sekarang tergantung kesadaran masing-masing',
            'explanation_D1' => 'Ada satgas dari guru dengan berbagai macam mata pelajaran',
            'explanation_D2' => 'Ya di buat protokol kesehatan',
            'explanation_D3' => 'Tidak deperkenankan belajar di sekolah dan harus isolasi diri di bawah pengawasan puskesmas',
            'explanation_D4' => 'Ya terdapat pamphlet di madding dan sekarang sudah tidak di tempel lagi',
            'explanation_D5' => 'Siswa datang bermasker, cuci tangan di tempat cuci tangan di dekat lapangan upacara, lalu di ukur suhu dengan thermogun, jalur masuk dan pulang juga dibedakan, wajib vaksin Covid-19 1 & 2',
            'explanation_D6' => 'Kantin sehat dengan jenis jajanan dan proses penyajian yang tertutup',
            'explanation_E1' => 'Tidak ada kasus setahun terakhir maupun sejak dari awal Covid-19',
            'explanation_E2' => 'Tidak ada kasus (0 kasus)',
            'explanation_E3' => 'Tidak ada pemusatan pada kelas tertentu karena yang terkena Covid-19 di suruh isolasi mandiri di rumah',
            'notes' => '',
        ]);
        // SMP NEGERI 13 [5]
        Infrastructure::create([
            'school_id' => 5, 'school_address' => 'Jl. Lamongan Raya Sampangan', 'school_bp' => 'SMP',
            'A1' => '10639',
            'A2' => '3455',
            'A3' => '27',
            'A4' => '63',
            'A5' => '22.8',
            'B1' => '41',
            'B2' => '863',
            'B3' => '386',
            'B4' => '477',
            'B5' => '12',
            'C1' => '10',
            'C2' => '9',
            'C3' => 'Baik',
            'C4' => '27',
            'C5' => '1',
            'C6' => '27',
            'C7' => '27',
            'C8' => '1',
            'C9' => '50',
            'C10' => 'Tidak Baik',
            'D1' => 'Ya',
            'D2' => 'Ya',
            'D3' => 'Ya',
            'D4' => 'Ya',
            'D5' => 'Ya',
            'D6' => 'Ya',
            'E1' => '0',
            'E2' => '0',
            'E3' => 'Tidak',
            'explanation_A1' => '10.639 m2',
            'explanation_A2' => '3.455 m2',
            'explanation_A3' => '27 kelas',
            'explanation_A4' => '7 m × 9 m = 63 m2',
            'explanation_A5' => '12 buah (1,9 m × 1 m)',
            'explanation_B1' => '41 orang (Laki-laki = 10 orang, Perempuan = 31 orang)',
            'explanation_B2' => '863 Siswa, tiap kelas 32 Siswa',
            'explanation_B3' => 'Laki-laki = 386 Siswa',
            'explanation_B4' => 'Perempuan = 477 Siswa',
            'explanation_B5' => '12 orang (Laki-laki = 6 orang, Perempuan = 6 orang)',
            'explanation_C1' => 'Laki-laki = 10 buah',
            'explanation_C2' => 'Perempuan = 9 buah',
            'explanation_C3' => 'Ya selalu mengalir (bak mandi dan keran air mengalir)',
            'explanation_C4' => 'Jumlah yang disediakan 27 sabun cuci tangan dibagi dengan jumlah kelas 27',
            'explanation_C5' => 'Dibersihkan setiap seminggu sekali',
            'explanation_C6' => 'Jumlah yang disediakan 27 tempat cuci tangan dibagi dengan jumlah kelas 27',
            'explanation_C7' => 'Jumlah handsanitizer yang disediakan 27 dibagi dengan jumlah kelas 27',
            'explanation_C8' => 'Ada tersedia (dulu di depan sekolah dan saat masuk sekolah)',
            'explanation_C9' => 'Disediakan masker cadangan (50 pcs) dari jumlah siswa 863',
            'explanation_C10' => 'Dulu selalu bermasker dan sekarang tergantung kesadaran masing-masing',
            'explanation_D1' => 'Ada satgas dari guru dengan berbagai macam mata pelajaran sebanyak ±7 orang',
            'explanation_D2' => 'Ya dilakukan sosialisasi dengan cara lisan',
            'explanation_D3' => 'Suruh isolasi mandiri di rumah dan pakai surat ijin dari puskesmas',
            'explanation_D4' => 'Ya terdapat poster dan stiker di tempat cuci tangan',
            'explanation_D5' => 'Ya di buat protokol kesehatan (siswa memakai masker, jaga jarak dan cuci tangan)',
            'explanation_D6' => 'Kantin sehat dengan jenis jajanan dan proses penyajian yang tertutup dan ada keran 1 buah bukan bak cuci tangan',
            'explanation_E1' => 'Tidak ada kasus setahun terakhir tahun 2021 terdapat kasus 3 orang guru dan anak 2-3 orang',
            'explanation_E2' => 'Tidak ada kasus (0 kasus)',
            'explanation_E3' => 'Tidak ada pemusatan pada kelas tertentu karena yang terkena Covid-19 di suruh isolasi mandiri di rumah',
            'notes' => '',
        ]);
        // MTs AL ASROR [6]
        Infrastructure::create([
            'school_id' => 6, 'school_address' => 'Jl. Legoksari Raya No 02 RT 03 RW 2, Patemon, Kecamatan Gunungpati, Semarang, 50256', 'school_bp' => 'SMP',
            'A1' => '4623',
            'A2' => '1200',
            'A3' => '26',
            'A4' => '56',
            'A5' => '1.68',
            'B1' => '20',
            'B2' => '763',
            'B3' => '400',
            'B4' => '363',
            'B5' => '2',
            'C1' => '4',
            'C2' => '5',
            'C3' => 'Baik',
            'C4' => '13',
            'C5' => '1',
            'C6' => '13',
            'C7' => '13',
            'C8' => '2',
            'C9' => '50',
            'C10' => 'Tidak Baik',
            'D1' => 'Ya',
            'D2' => 'Ya',
            'D3' => 'Ya',
            'D4' => 'Tidak',
            'D5' => 'Ya',
            'D6' => 'Ya',
            'E1' => '0',
            'E2' => '0',
            'E3' => 'Tidak',
            'explanation_A1' => '4623 m2',
            'explanation_A2' => '1200 m2',
            'explanation_A3' => '26 kelas',
            'explanation_A4' => '7 m × 8 m = 56 m2',
            'explanation_A5' => '4 buah jendela (0,4 m × 0,6 m) dan 6 lubang angin (0,4 m × 0,3 m)',
            'explanation_B1' => '20 orang (Laki-laki = 10 orang, Perempuan = 10 orang)',
            'explanation_B2' => '763 Siswa',
            'explanation_B3' => 'Laki-laki = 400 Siswa',
            'explanation_B4' => 'Perempuan = 363 Siswa',
            'explanation_B5' => '2 orang (Laki-laki = 1 orang, Perempuan = 1 orang)',
            'explanation_C1' => 'Laki-laki = 4 buah',
            'explanation_C2' => 'Perempuan = 5 buah',
            'explanation_C3' => 'Ya selalu mengalir (ember dan keran air mengalir)',
            'explanation_C4' => 'Jumlah yang disediakan 13 sabun cuci tangan dibagi dengan jumlah kelas 26',
            'explanation_C5' => 'Dibersihkan setiap seminggu sekali',
            'explanation_C6' => 'Jumlah yang disediakan 13 tempat cuci tangan dibagi dengan jumlah kelas 26',
            'explanation_C7' => 'Jumlah handsanitizer yang disediakan 13 dibagi dengan jumlah kelas 26',
            'explanation_C8' => 'Dulu ada dan selalu digunakan saat baru masuk ke sekolah',
            'explanation_C9' => 'Disediakan masker cadangan (50 pcs) dari jumlah siswa 763',
            'explanation_C10' => 'Dulu selalu bermasker dan sekarang tergantung kesadaran masing-masing',
            'explanation_D1' => 'Ada satgas dari guru dengan berbagai macam mata pelajaran',
            'explanation_D2' => 'Ya di buat protokol kesehatan',
            'explanation_D3' => 'Tidak deperkenankan belajar di sekolah dan harus isolasi diri di bawah pengawasan puskesmas',
            'explanation_D4' => 'Ya terdapat pamphlet di madding dan sekarang sudah tidak di tempel lagi',
            'explanation_D5' => 'Siswa datang bermasker, cuci tangan di tempat cuci tangan di dekat lapangan upacara, lalu di ukur suhu dengan thermogun, jalur masuk dan pulang juga dibedakan, wajib vaksin Covid-19 1 & 2',
            'explanation_D6' => 'Kantin sehat dengan jenis jajanan dan proses penyajian yang tertutup',
            'explanation_E1' => 'Tidak ada kasus setahun terakhir maupun sejak dari awal Covid-19',
            'explanation_E2' => 'Tidak ada kasus (0 kasus)',
            'explanation_E3' => 'Tidak ada pemusatan pada kelas tertentu karena yang terkena Covid-19 di suruh isolasi mandiri di rumah',
            'notes' => '',
        ]);
        // SD NEGERI BENDAN NGISOR [7]
        Infrastructure::create([
            'school_id' => 7, 'school_address' => 'Jl. Lamongan Raya No 60 Semarang', 'school_bp' => 'SD',
            'A1' => '2160',
            'A2' => '360',
            'A3' => '12',
            'A4' => '56',
            'A5' => '6',
            'B1' => '19',
            'B2' => '334',
            'B3' => '158',
            'B4' => '176',
            'B5' => '1',
            'C1' => '4',
            'C2' => '3',
            'C3' => 'Baik',
            'C4' => '12',
            'C5' => '1',
            'C6' => '12',
            'C7' => '12',
            'C8' => '1',
            'C9' => '50',
            'C10' => 'Baik',
            'D1' => 'Ya',
            'D2' => 'Ya',
            'D3' => 'Ya',
            'D4' => 'Ya',
            'D5' => 'Ya',
            'D6' => 'Ya',
            'E1' => '0',
            'E2' => '0',
            'E3' => 'Tidak',
            'explanation_A1' => '2.160 m2',
            'explanation_A2' => '360 m2',
            'explanation_A3' => '12 kelas',
            'explanation_A4' => '56 m2 atau 7 m × 8 m',
            'explanation_A5' => 'jendela 2 m × 1 m = 4 buah dan lubang angin 1 m × 1 m = 2 buah',
            'explanation_B1' => '19 orang (laki-laki = 2 orang, perempuan = 16 orang dan 1 kepala sekolah perempuan)',
            'explanation_B2' => '334 siswa',
            'explanation_B3' => 'Laki-laki = 158 siswa',
            'explanation_B4' => 'Perempuan = 176 siswa',
            'explanation_B5' => '1 orang',
            'explanation_C1' => 'Laki-laki 1 buah dan 2 urinoir dan tiap 1 tempat terdapat 3 urinoir',
            'explanation_C2' => 'Perempuan 4 buah',
            'explanation_C3' => 'Selalu ada di ember',
            'explanation_C4' => 'Jumlah yang disediakan 12 sabun cuci tangan dibagi dengan jumlah kelas 12',
            'explanation_C5' => 'Dibersihkan setiap seminggu sekali',
            'explanation_C6' => 'Jumlah yang disediakan 12 tempat cuci tangan dibagi dengan jumlah kelas 12',
            'explanation_C7' => 'Jumlah handsanitizer yang disediakan 12 dibagi dengan jumlah kelas 12',
            'explanation_C8' => 'Jarang digunakan sejak pemberitahuan presiden',
            'explanation_C9' => 'Disediakan masker cadangan (50 pcs) dari jumlah siswa 334',
            'explanation_C10' => 'Ya masih menggunakan masker di kelas dan ketika saat jam olahraga masker di lepas',
            'explanation_D1' => 'Ada dengan guru olahraga sebagai satgas Covid-19 di sekolah',
            'explanation_D2' => 'Dilakukan sosialisasi PPT dari guru sebelum pembelajaran setiap pagi',
            'explanation_D3' => 'Langsung di rujuk ke puskesmas lalu semua siswa yang sakit belajar di rumah',
            'explanation_D4' => 'Ada hanya dari guru serta sosialisasi saat upacara setiap hari senin',
            'explanation_D5' => 'Ada dengan memakai masker saat di kelas',
            'explanation_D6' => 'Ada dan menerapkan kantin sehat  dengan 2 tempat cuci tangan',
            'explanation_E1' => 'Setahun terakhir tidak ada kasus',
            'explanation_E2' => 'Tidak ada kasus (0 kasus)',
            'explanation_E3' => 'Tidak ada pemusatan pada kelas tertentu karena yang terkena Covid-19 di suruh isolasi mandiri di rumah',
            'notes' => '',
        ]);
        // SD NEGERI PETOMPON 02 [8]
        Infrastructure::create([
            'school_id' => 8, 'school_address' => 'Jl. Kelud Raya No 5 Semarang', 'school_bp' => 'SD',
            'A1' => '2569',
            'A2' => '600',
            'A3' => '18',
            'A4' => '49',
            'A5' => '6',
            'B1' => '22',
            'B2' => '526',
            'B3' => '266',
            'B4' => '260',
            'B5' => '2',
            'C1' => '7',
            'C2' => '7',
            'C3' => 'Baik',
            'C4' => '18',
            'C5' => '1',
            'C6' => '18',
            'C7' => '18',
            'C8' => '1',
            'C9' => '50',
            'C10' => 'Baik',
            'D1' => 'Ya',
            'D2' => 'Ya',
            'D3' => 'Ya',
            'D4' => 'Ya',
            'D5' => 'Ya',
            'D6' => 'Ya',
            'E1' => '0',
            'E2' => '0',
            'E3' => 'Tidak',
            'explanation_A1' => '2.569 m2',
            'explanation_A2' => '600 m2',
            'explanation_A3' => '18 kelas',
            'explanation_A4' => '7 × 7 m2',
            'explanation_A5' => '4-6 jendela (p = 1 m dan l = 1 m)',
            'explanation_B1' => '22 orang (laki-laki = 3 orang, perempuan = 19 orang)',
            'explanation_B2' => '526 siswa',
            'explanation_B3' => 'Laki-laki = 266 siswa',
            'explanation_B4' => 'Perempuan = 260 siswa',
            'explanation_B5' => '2 orang',
            'explanation_C1' => '6 KM laki-laki, 1 KM kepala sekolah, dan 1 KM guru&staf',
            'explanation_C2' => '6 KM perempuan',
            'explanation_C3' => 'Selalu ada di ember',
            'explanation_C4' => 'Jumlah yang disediakan 18 sabun cuci tangan dibagi dengan jumlah kelas 18',
            'explanation_C5' => 'Dibersihkan setiap seminggu sekali',
            'explanation_C6' => 'Jumlah yang disediakan 18 tempat cuci tangan dibagi dengan jumlah kelas 18',
            'explanation_C7' => 'Jumlah handsanitizer yang disediakan 18 dibagi dengan jumlah kelas 18',
            'explanation_C8' => 'Ada thermogun dan untuk mengecek suhu tubuh setiap senin sehabis upacara',
            'explanation_C9' => 'Disediakan masker cadangan (50 pcs) dari jumlah siswa 526',
            'explanation_C10' => 'Ya masih menggunakan masker di kelas dan ketika di luar ruangan sudah tidak menggunakan masker',
            'explanation_D1' => 'Ada dengan guru sebagai satgas covid-19',
            'explanation_D2' => 'Dilakukan sosialisasi rutin setiap upacara serta di dalam kelas',
            'explanation_D3' => 'Melakukan tes swab lalu meminta ke puskesmas untuk surat cuti sampai sembuh. Sekolah dan puskesmas juga memantau perkembangan kesehatan',
            'explanation_D4' => 'Ada MMT dan buku kesehatan',
            'explanation_D5' => 'Ada dengan memakai masker, mencuci tangan sebelum masuk kelas kemudian cek suhu tubuh setiap hari senin sehabis upacara',
            'explanation_D6' => 'Ada dan menerapkan kantin sehat',
            'explanation_E1' => 'Tidak ada kasus Covid-19 setahun terakhir tetapi tahun 2020-2021 ada',
            'explanation_E2' => 'Tidak ada kasus (0 kasus)',
            'explanation_E3' => 'Tidak ada pemusatan pada kelas tertentu karena yang terkena Covid-19 di suruh isolasi mandiri di rumah',
            'notes' => '',
        ]);
        // SD NEGERI SUKOREJO 02 [9]
        Infrastructure::create([
            'school_id' => 9, 'school_address' => 'Jl. Dewi Sartika Barat IV/A Sukorejo Gunungpati, Semarang 50221', 'school_bp' => 'SD',
            'A1' => '2177',
            'A2' => '302',
            'A3' => '6',
            'A4' => '56',
            'A5' => '7.2',
            'B1' => '9',
            'B2' => '176',
            'B3' => '88',
            'B4' => '88',
            'B5' => '2',
            'C1' => '4',
            'C2' => '4',
            'C3' => 'Baik',
            'C4' => '6',
            'C5' => '1',
            'C6' => '6',
            'C7' => '6',
            'C8' => '2',
            'C9' => '50',
            'C10' => 'Tidak Baik',
            'D1' => 'Ya',
            'D2' => 'Ya',
            'D3' => 'Ya',
            'D4' => 'Tidak',
            'D5' => 'Ya',
            'D6' => 'Tidak',
            'E1' => '0',
            'E2' => '0',
            'E3' => 'Tidak',
            'explanation_A1' => '2.177 m2',
            'explanation_A2' => '302 m2',
            'explanation_A3' => '6 kelas',
            'explanation_A4' => 'Kelas 1 & 2 = 56 m2 dan Kelas 3,4,5,6 = 52,5 m2',
            'explanation_A5' => '6 jendela (p=3 m dan l=0,4 m)',
            'explanation_B1' => '9 orang',
            'explanation_B2' => 'Total = 176 siswa, kelas 1,2,3=28 siswa, Kelas 4=30 siswa, kelas 5,6=28 siswa',
            'explanation_B3' => '-',
            'explanation_B4' => '-',
            'explanation_B5' => '2 orang',
            'explanation_C1' => '4 buah',
            'explanation_C2' => '4 buah',
            'explanation_C3' => 'Selalu ada di ember',
            'explanation_C4' => 'Jumlah yang disediakan 6 sabun cuci tangan dibagi dengan jumlah kelas 6',
            'explanation_C5' => 'Dibersihkan setiap seminggu sekali',
            'explanation_C6' => 'Jumlah yang disediakan 6 tempat cuci tangan dibagi dengan jumlah kelas 6',
            'explanation_C7' => 'Jumlah handsanitizer yang disediakan 6 dibagi dengan jumlah kelas 6',
            'explanation_C8' => 'Ada 4 thermogun dan sejak hari senin 9 januari 2023 tidak melakukan pengecekan suhu tubuh',
            'explanation_C9' => 'Disediakan masker cadangan (50 pcs) dari jumlah siswa 176',
            'explanation_C10' => 'Sudah melonggarkan penggunaan masker di luar kelas dan jam istirahat bebas tanpa masker, di kelas pakai masker',
            'explanation_D1' => 'Ada dengan 9 guru terlibat menjadi satgas Covid-19',
            'explanation_D2' => 'Selalu dilakukan lewat whatsapp informasi mengenai prokes Covid-19',
            'explanation_D3' => 'Pengumuman dari puskesmas dikabarkan ke PKK kelurahan dan ke sekolah',
            'explanation_D4' => 'Sebelumnya ada tetapi sudah di copot dari mading sekolah',
            'explanation_D5' => 'Ada dengan memakai masker dari rumah, membawa hand sanitizer, alat makan sendiri',
            'explanation_D6' => 'Tidak ada karena tidak ada yang mau membuat kantin sehat di sekolah Ketika ditawarkan ke orang tua murid',
            'explanation_E1' => 'Tidak ada kasus Covid-19 setahun terakhir tetapi tahun 2020-2021 ada',
            'explanation_E2' => 'Tidak ada kasus (0 kasus)',
            'explanation_E3' => 'Tidak ada pemusatan pada kelas tertentu karena yang terkena Covid-19 di suruh isolasi mandiri di rumah',
            'notes' => '',
        ]);
    }
}
